<#
    Installation of the AX206 panel as a scheduled task.

    .\deploy\install-task.ps1              installs / updates
    .\deploy\install-task.ps1 -Uninstall   removes the task (leaves the venv and configuration)

    What it does:
      1. creates a venv OUTSIDE the repo (%LOCALAPPDATA%\claude-usage-monitor\panel-venv)
      2. installs from requirements.txt
      3. places a panel-run.pyw redirection next to the configuration, pointing at the repo
      4. registers the task "Claude Panel AX206" on user logon
      5. starts it and waits until the log confirms that the panel is drawing

    Notes:
      * "Run only when user is logged on" is REQUIRED: a network drive is a drive
        mapped per session, and USB access requires an interactive session.
      * ExecutionTimeLimit MUST be zero. The default "stop after 3 days"
        would kill the panel once a week, without a trace in the log.
      * pythonw.exe, not python.exe -- otherwise a console pops up at every logon.
      * This file is kept in PURE ASCII. PowerShell 5.1 reads a file without a BOM
        as ANSI, so the U+2014 dash breaks apart into three bytes, of which 0x94 is
        the closing quote U+201D -- and the parser takes it for the end of a string
        and falls over a few dozen lines further on, in a spot with no connection
        to the cause. No dash is worth that.
      * REGISTRATION IS NOT A START. The trigger is on logon, so during an
        installation on an already logged-on session the task simply sits idle. A script
        that ended at "registered" left the screen dark without
        any hint at all -- and tempted a second run.
      * The handle to the panel is EXCLUSIVE. While another program holds it, the client
        retries every 30 s and writes about it in the log ONCE (not every second), and
        another program's image stays on the glass. From outside this looks exactly like
        a failed installation, so the script reads the log after start and names it outright.
#>
[CmdletBinding()]
param(
    [switch]$Uninstall,
    # The name is a leftover from the single-screen days. Renaming does NOT move the task:
    # the old one would stay registered next to the new one and two clients would fight
    # over the same display.
    [string]$TaskName = "Claude Panel AX206",
    # How many screens panel.json declares. The script does not read that file (at
    # the first installation it does not exist yet), and without this number an "OK"
    # after the first line to report in would mean "drawing one screen out of two".
    [int]$Panels = 1
)

$ErrorActionPreference = "Stop"

$PanelDir = Split-Path -Parent $PSScriptRoot
$AppDir   = Join-Path $env:LOCALAPPDATA "claude-usage-monitor"
$VenvDir  = Join-Path $AppDir "panel-venv"
$Pythonw  = Join-Path $VenvDir "Scripts\pythonw.exe"
$Launcher = Join-Path $AppDir "panel-run.pyw"

function Get-PanelProcess {
    # By command line, not by name: pythonw.exe also runs
    # other things, and killing an unrelated process would be worse than the problem
    # being solved here. There are usually two instances -- the venv stub and its child.
    @(Get-CimInstance Win32_Process -Filter "Name = 'pythonw.exe'" -ErrorAction SilentlyContinue |
        Where-Object { $_.CommandLine -like "*panel-run.pyw*" })
}

if ($Uninstall) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "removed task '$TaskName'"
    } else {
        Write-Host "task '$TaskName' did not exist"
    }
    Write-Host "venv and panel.json remain in $AppDir"
    return
}

Write-Host "panel: $PanelDir"
New-Item -ItemType Directory -Force $AppDir | Out-Null

# --- 1. venv --------------------------------------------------------------
if (-not (Test-Path $Pythonw)) {
    Write-Host "creating venv in $VenvDir"
    $base = (Get-Command python).Source
    & $base -m venv $VenvDir
    if ($LASTEXITCODE -ne 0) { throw "failed to create venv" }
}
Write-Host "installing dependencies"
& (Join-Path $VenvDir "Scripts\python.exe") -m pip install --quiet --upgrade pip
if ($LASTEXITCODE -ne 0) { throw "pip: pip upgrade failed" }
& (Join-Path $VenvDir "Scripts\python.exe") -m pip install --quiet -r (Join-Path $PanelDir "requirements.txt")
if ($LASTEXITCODE -ne 0) { throw "pip install -r requirements.txt failed" }

# --- 2. redirection -------------------------------------------------------
# The same convention as with the probe: the source stays in the repo, here sit a
# few lines that run it. Editing in the repo takes effect at once.
$launcherBody = @"
# Generated by panel/deploy/install-task.ps1 -- do not edit by hand.
# The panel lives in the repo; this is only a redirection.
import os, runpy, sys, time

SRC = r"$PanelDir"

# A network drive can be unmapped when the task fires right after logon.
waited = 0
while not os.path.isdir(SRC) and waited < 120:
    time.sleep(2)
    waited += 2

sys.path.insert(0, SRC)
runpy.run_path(os.path.join(SRC, "run.pyw"), run_name="__main__")
"@
Set-Content -Path $Launcher -Value $launcherBody -Encoding utf8
Write-Host "redirection: $Launcher"

# --- 3. task --------------------------------------------------------------
# Stop BEFORE registering, not after: -Force on a running task leaves the old
# process alive. Without this, what was there before would keep running instead of
# what was just installed -- and silently, because the image on the panel looks the same.
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing -and $existing.State -eq "Running") {
    Write-Host "stopping the previous instance"
    Stop-ScheduledTask -TaskName $TaskName
    # Wait for the PROCESS TO DIE, not for the task state. The scheduler reports
    # "Ready" as soon as it sends the signal, while pythonw lives on a moment longer and
    # holds the panel.lock lock. A new instance would then walk into a taken lock,
    # quietly exit, and the OLD code would keep drawing -- that is, the installation
    # would look successful while changing nothing.
    $deadline = (Get-Date).AddSeconds(20)
    while ((Get-Date) -lt $deadline -and (Get-PanelProcess)) {
        Start-Sleep -Milliseconds 500
    }
    if (Get-PanelProcess) {
        Write-Host "  WARNING: the panel process is still alive after 20 s - the new instance may not take over"
    }
}

$action = New-ScheduledTaskAction -Execute $Pythonw -Argument "`"$Launcher`"" -WorkingDirectory $AppDir
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$trigger.Delay = "PT30S"

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -RestartCount 99 `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0)   # 0 = no limit; see the header

$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings -Principal $principal -Force `
    -Description "Limity Claude na panelu USB AX206 (repo: $PanelDir)" | Out-Null

# --- 4. start and confirmation --------------------------------------------
# Wait for a LINE IN THE LOG, not for "State = Running". A task can be
# running and at the same time draw nothing: a busy panel, a bad token, no
# network. "Running" would be telling an untruth then.
$LogPath = Join-Path $AppDir "panel.log"
$before = 0
if (Test-Path $LogPath) { $before = @(Get-Content $LogPath).Count }

Start-ScheduledTask -TaskName $TaskName
Write-Host ""
Write-Host "task '$TaskName' registered and started"
Write-Host -NoNewline "waiting for confirmation from the log "

# How many screens must report in. The script does NOT read panel.json -- during
# installation that file often does not exist yet (there is a separate branch for it
# below), so the number is given by hand: .\install-task.ps1 -Panels 2
$deadline = (Get-Date).AddSeconds(30)
$opened = @(); $unacked = @(); $busy = $null; $dup = $null; $bad = $null
while ((Get-Date) -lt $deadline) {
    Start-Sleep -Seconds 2
    Write-Host -NoNewline "."
    $new = @()
    if (Test-Path $LogPath) { $new = @(Get-Content $LogPath | Select-Object -Skip $before) }
    # Wait for the FIRST FRAME, not for "opened". A handle to the device
    # does not draw anything yet, and it was the missing frame that was the symptom
    # which had everything installed a second time.
    #
    # Collect ALL the lines, not the last one: with two screens one may be
    # drawing while the other is busy -- and an "OK" after the first matching line
    # would sweep that under the rug.
    $opened  = @($new | Where-Object { $_ -match "first frame after opening" })
    $unacked = @($new | Where-Object { $_ -match "not acknowledged" })
    $busy    = $new | Where-Object { $_ -match "held by another process" } | Select-Object -Last 1
    $dup     = $new | Where-Object { $_ -match "panel already running" }   | Select-Object -Last 1
    $bad     = $new | Where-Object { $_ -match "config error:" }           | Select-Object -Last 1
    if (($opened.Count + $unacked.Count) -ge $Panels -or $busy -or $dup -or $bad) { break }
}
Write-Host ""
Write-Host ""

if ($opened.Count + $unacked.Count -gt 0) {
    $reported = $opened.Count + $unacked.Count
    if ($reported -lt $Panels) {
        Write-Host "WARNING - $reported of $Panels screens reported in:"
    } else {
        Write-Host "OK - panel is drawing ($reported of $Panels):"
    }
    foreach ($line in $opened) { Write-Host "  $line" }
    foreach ($line in $unacked) {
        # This driver acknowledges NOTHING: the line only says that the bytes
        # went out. A screen unplugged, rotated or skewed will write down
        # exactly the same, so there is nothing here to count as "drawing".
        Write-Host "  $line"
        Write-Host "    ^ unacknowledged - check with your eyes whether anything is visible"
    }
} elseif ($busy) {
    Write-Host "PANEL BUSY - another process has it:"
    Write-Host "  $busy"
    Write-Host ""
    Write-Host "  The handle to the module is exclusive - either the panel or the other program."
    Write-Host "  Stop that program (or point it at the second module). The client keeps"
    Write-Host "  retrying every 30 s and will resume drawing ON ITS OWN once the panel frees up;"
    Write-Host "  no need to restart it or install it again."
} elseif ($dup) {
    Write-Host "PANEL WAS ALREADY RUNNING - the new instance backed off at the lock:"
    Write-Host "  $dup"
    Write-Host "  This is not an error. The one that was already running keeps drawing."
} elseif ($bad) {
    Write-Host "CONFIGURATION ERROR - the panel will not start:"
    Write-Host "  $bad"
    Write-Host "  Fix $AppDir\panel.json and run: Start-ScheduledTask -TaskName '$TaskName'"
} else {
    Write-Host "NO CONFIRMATION within 30 s. Check the log - its tail is below:"
    if (Test-Path $LogPath) { Get-Content $LogPath -Tail 8 | ForEach-Object { Write-Host "  $_" } }
}

Write-Host ""
Write-Host "  log:     $LogPath"
Write-Host "  config:  $AppDir\panel.json"
Write-Host "  stop:    Stop-ScheduledTask -TaskName '$TaskName'"
Write-Host "  start:   Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  test:    python -m panel --probe   (stop the task first)"
